#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Finder\Finder;

(new Application('init', '1.0.0'))
    ->register('init')
    ->setCode(function(InputInterface $input, OutputInterface $output) {
        $questionHelper = new QuestionHelper();
        $finder = new Finder();

        $vendor = $questionHelper->ask($input, $output, new Question('What is your plugin namespace (usually this is your organization name)? '));

        $q = new Question('What is your plugin name ("Plugin" will be appended to the plugin name)? ');
        $q->setValidator(static function ($answer) {
            if (!is_string($answer) || 'Plugin' === substr($answer, -6)) {
                throw new \RuntimeException(
                    'The name of the plugin should not include "Plugin". That will be appended automatically'
                );
            }

            return $answer;
        });
        $pluginName = $questionHelper->ask($input, $output, $q);
        $pluginNameWithSuffix = $pluginName . 'Plugin';

        $symfonyPath = '@' . $vendor . $pluginNameWithSuffix;

        $yamlNamespace = Container::underscore($vendor) . '_' . Container::underscore($pluginName);
        if(substr($yamlNamespace, -7) === '_plugin') {
            $yamlNamespace = substr($yamlNamespace, 0, -7);
        }

        $finder
            ->in(['src', 'tests'])
            ->name('*.yaml')
            ->name('*.php')
            ->contains('acme_sylius_example')
            ->contains('@AcmeSyliusExamplePlugin')
            ->contains('Acme\\SyliusExamplePlugin')
            ->contains('AcmeSyliusExample')
        ;

        foreach ($finder as $file) {
            replaceInFile($file->getPathname(), [
                'acme_sylius_example' => $yamlNamespace,
                '@AcmeSyliusExamplePlugin' => $symfonyPath,
                'Acme\\SyliusExamplePlugin' => $vendor . '\\' . $pluginNameWithSuffix,
                'AcmeSyliusExample' => $vendor.$pluginName,
            ]);
        }


        replaceInFile('composer.json', [
            'setono/sylius-plugin-skeleton' => str_replace('_', '-', Container::underscore($vendor)) . '/' . str_replace('_', '-', Container::underscore($pluginNameWithSuffix)),
            'Acme\\\\SyliusExamplePlugin' => $vendor . '\\\\' . $pluginNameWithSuffix,
        ]);

        replaceInFile('phpspec.yml.dist', ['Acme\\SyliusExamplePlugin' => $vendor . '\\' . $pluginNameWithSuffix]);
        replaceInFile('phpunit.xml.dist', ['AcmeSyliusExamplePlugin' => $vendor.$pluginNameWithSuffix]);
        replaceInFile('LICENSE', ['Acme' => $vendor]);

        rename('src/DependencyInjection/AcmeSyliusExampleExtension.php', sprintf('src/DependencyInjection/%s%sExtension.php', $vendor, $pluginName));
        rename('src/AcmeSyliusExamplePlugin.php', sprintf('src/%s%s.php', $vendor, $pluginNameWithSuffix));
        rename('tests/DependencyInjection/AcmeSyliusExampleExtensionTest.php', sprintf('tests/DependencyInjection/%s%sExtensionTest.php', $vendor, $pluginName));
    })
    ->getApplication()
    ->setDefaultCommand('init', true) // Single command application
    ->run()
;

function replaceInFile(string $file, array $replacements): void
{
    $search = array_keys($replacements);
    $replace = array_values($replacements);

    $data = file_get_contents($file);
    file_put_contents($file, str_replace($search, $replace, $data));
}
