acme_sylius_example_shop:
    resource: "@AcmeSyliusExamplePlugin/Resources/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

acme_sylius_example_admin:
    resource: "@AcmeSyliusExamplePlugin/Resources/config/routes/admin.yaml"
    prefix: /admin
