name: "backwards-compatibility-check"
on:
    push:
        branches:
            - "master"
        paths-ignore:
            - "**/*.md"
    pull_request:
        paths-ignore:
            - "**/*.md"
    workflow_dispatch: ~

jobs:
    backwards-compatibility-check:
        name: "Backwards Compatibility Check"

        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v3"
                with:
                    fetch-depth: 0

            -   name: "Check for BC breaks"
                uses: "docker://nyholm/roave-bc-check-ga"
