name: Merge

on:
    workflow_run:
        types:
            - "completed"
        workflows:
            - "build"

jobs:
    merge:
        # todo create a step that fetches the title of the pull request (if any) and outputs that title, so we can use:
        # startsWith(github.event.pull_request.title, 'composer(deps-dev)')
        
        name: "Merge"
        runs-on: "ubuntu-latest"
        steps:
            -   if: ${{ github.event.workflow_run.conclusion == 'success' }}
                name: Merge
                uses: ridedott/merge-me-action@v2
                with:
                    # Depending on branch protection rules, a  manually populated
                    # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
                    # a protected branch must be used. This secret can have an arbitrary
                    # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
                    #
                    # When using a custom token, it is recommended to leave the following
                    # comment for other developers to be aware of the reasoning behind it:
                    #
                    # This must be used as GitHub Actions token does not support pushing
                    # to protected branches.
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
