name: "Test"

on:
    pull_request: ~

jobs:
    test:
        name: "Test"

        runs-on: "ubuntu-latest"

        steps:
            -   run: "echo ${{ github.event.pull_request.head.ref }}"
            -   run: "echo ${{ github.event.pull_request.base.ref }}"
